ktor {
    development = true
    deployment {
        port = 8080
        host = "0.0.0.0"
    }
    application {
        modules = [ com.cattery.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/cattery"
    user = "cattery"
    password = "cattery"
    driver = "org.postgresql.Driver"
    maxPoolSize = 10
}

jwt {
    secret = "cattery-dev-secret-change-in-production-min-256-bits!!"
    issuer = "cattery-api"
    audience = "cattery-app"
    realm = "Cattery"
    expirationMs = 604800000
}

flyway {
    locations = "classpath:db/migration"
}
