CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    password_hash CLOB NOT NULL,
    name VARCHAR(200) NOT NULL,
    avatar_url CLOB,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cat_females (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INT NOT NULL,
    name VARCHAR(200) NOT NULL,
    birth_date DATE NOT NULL,
    mating_date DATE,
    birth_due_date DATE,
    photo_urls CLOB NOT NULL DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cat_females_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cat_males (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INT NOT NULL,
    name VARCHAR(200) NOT NULL,
    birth_date DATE NOT NULL,
    photo_urls CLOB NOT NULL DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cat_males_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS litters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INT NOT NULL,
    name VARCHAR(10) NOT NULL,
    birth_date DATE NOT NULL,
    total_count INT NOT NULL DEFAULT 0,
    male_count INT NOT NULL DEFAULT 0,
    female_count INT NOT NULL DEFAULT 0,
    mother_id INT,
    father_id INT,
    photo_urls CLOB NOT NULL DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_litters_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_litters_mother FOREIGN KEY (mother_id) REFERENCES cat_females(id) ON DELETE SET NULL,
    CONSTRAINT fk_litters_father FOREIGN KEY (father_id) REFERENCES cat_males(id) ON DELETE SET NULL,
    CONSTRAINT uq_litters_owner_name UNIQUE (owner_id, name)
);

CREATE TABLE IF NOT EXISTS kittens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    litter_id INT NOT NULL,
    name VARCHAR(200) NOT NULL,
    birth_date DATE NOT NULL,
    color VARCHAR(200) NOT NULL,
    birth_weight DECIMAL(5,2),
    status VARCHAR(20) NOT NULL DEFAULT 'FREE',
    photo_urls CLOB NOT NULL DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kittens_litter FOREIGN KEY (litter_id) REFERENCES litters(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reservations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitten_id INT NOT NULL,
    buyer_id INT NOT NULL,
    reserved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_reservations_kitten FOREIGN KEY (kitten_id) REFERENCES kittens(id) ON DELETE CASCADE,
    CONSTRAINT fk_reservations_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cat_females_owner ON cat_females(owner_id);
CREATE INDEX IF NOT EXISTS idx_cat_males_owner ON cat_males(owner_id);
CREATE INDEX IF NOT EXISTS idx_litters_owner ON litters(owner_id);
CREATE INDEX IF NOT EXISTS idx_kittens_litter ON kittens(litter_id);
CREATE INDEX IF NOT EXISTS idx_kittens_status ON kittens(status);
CREATE INDEX IF NOT EXISTS idx_reservations_buyer ON reservations(buyer_id);
CREATE INDEX IF NOT EXISTS idx_reservations_kitten ON reservations(kitten_id);
